### ISSUE TITLE
User Journey

### ISSUE THREAD

**Issue by Balsam-Faysal** [FACG4/FACGTracker#3]
## As a facilitator I can : 
* track students attendance and behavior 
* give them feedback and red flags
 so that I can save time and improve student behavior .
 # Acceptance criteria : 

- [x] Login #5 
- [x] Home page #7 
- [x] Manege students (view , delete ) #11
- [x] Invite students #12 
- [x] Student profile   #8
- [x] Add feedback #9
- [x] Add red flag with its type #10 
- [x] Complaints and suggestions #15
- [ ] Reports #13
- [x] Take attendance #14
- [ ] Add and update weeks mentor and schedule  #16
- [x] Logout #6
